global:
    registry: nexus11.ru-central1.internal:9182
    imageCredentials:
        registry: nexus11.ru-central1.internal:9182
        username: admin
        password: 270685
        email: someone@host.com

ingress:
    annotations:
        kubernetes.io/ingress.class: nginx
    labels: {}
    host: mydiplom.dimi.link
    tlsSecretName: ''

