global:
    registry: nexus11.ru-central1.internal:9182
    imageCredentials:
        registry: nexus11.ru-central1.internal:9182
        username: 'admin'
        password: '270685'
        email: someone@host.com

java:
    options: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom

istio:
    enabled: false

ingress:
    annotations:
        kubernetes.io/ingress.class: nginx
    labels: {}
    host: ''
    tlsSecretName: ''

diplomapp:
    replicas: 1
    image:
        repo: mydiplom/diplom-app
        tag: "new"
        imagePullSecrets:
        - name: registry-pull-credentials
    resources:
        limits:
            cpu: 500m
            memory: 1000Mi
        requests:
            cpu: 300m
            memory: 300Mi
    service:
        type: ClusterIP